name: Build CV from Html

on:
  push:
    tags:
      - "v*.*.*"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write

jobs:
  convert_to_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Generate pdfs
        uses: fifsky/html-to-pdf-action@master
        with:
          name: 
          htmlFile: ./curriculo/index.html
          outputFile: ./cv.pdf
          pdfOptions: '{"height": "1318px", "width": "870px", "printBackground": true}'
      
      - name: Upload modifications
        uses: actions/upload-artifact@v1
        with:
          name: my-cv
          path: ./cv.pdf
          
      - name: Push modifications
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./cv.pdf
    