name: Build CV from Html

on:
  push:
    tags:
      - "v*.*.*"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write

jobs:
  convert_to_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Generate PT CV
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: ./curriculo/index.html
          outputFile: ./cv-pt.pdf
          pdfOptions: '{"height": "1318px", "width": "870px", "printBackground": true}'

      - name: Generate EN CV
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: ./curriculo/curriculo_en.html
          outputFile: ./cv-en.pdf
          pdfOptions: '{"height": "1318px", "width": "870px", "printBackground": true}'
      
      - name: Upload modifications
        uses: actions/upload-artifact@v3
        with:
          name: my-cv
          path: ./*.pdf
          
      - name: Push modifications
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./cv-pt.pdf
            ./cv-en.pdf
    